services:
  runner:
    privileged: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REPOSITORY_URL: https://github.com/mjun0812/flash-attention-prebuild-wheels
        PERSONAL_ACCESS_TOKEN: $PERSONAL_ACCESS_TOKEN
        GH_RUNNER_VERSION: 2.327.1
        RUNNER_NAME: self-hosted-runner
        RUNNER_GROUP: default
        RUNNER_LABELS: self-hosted
        TARGET_ARCH: x64
