name: Build wheels and upload to GitHub Releases

on:
  workflow_dispatch:

jobs:
  # #########################################################
  # Build wheels with GitHub hosted runner
  # #########################################################
  build_wheels_linux:
    name: Build Linux
    strategy:
      fail-fast: false
      matrix:
        flash-attn-version: ["2.6.3"]
        python-version: ["3.10"]
        torch-version: ["2.5.1"]
        # https://developer.nvidia.com/cuda-toolkit-archive
        cuda-version: ["12.4.1"]
    uses: ./.github/workflows/build_linux.yml
    with:
      flash-attn-version: ${{ matrix.flash-attn-version }}
      python-version: ${{ matrix.python-version }}
      torch-version: ${{ matrix.torch-version }}
      cuda-version: ${{ matrix.cuda-version }}
    secrets: inherit

  build_wheels_windows:
    name: Build Windows
    strategy:
      fail-fast: false
      matrix:
        flash-attn-version: ["2.6.3"]
        python-version: ["3.10"]
        torch-version: ["2.5.1"]
        # https://developer.nvidia.com/cuda-toolkit-archive
        cuda-version: ["12.4.1"]
    uses: ./.github/workflows/build_windows.yml
    with:
      flash-attn-version: ${{ matrix.flash-attn-version }}
      python-version: ${{ matrix.python-version }}
      torch-version: ${{ matrix.torch-version }}
      cuda-version: ${{ matrix.cuda-version }}
    secrets: inherit
