name: "Test self-hosted runner"
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on:
      - self-hosted
    timeout-minutes: 10
    container:
      image: docker:dind
    steps:
      - run: ls
      - run: pwd