name: "Docker and container hooks test"
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on:
      - self-hosted
    timeout-minutes: 10
    container:
      image: docker:dind
    steps:
      - name: Show docker info
        run: |
          docker -v
          docker info
          docker ps
      - run: ls
      - run: pwd