name: Build wheels and upload to GitHub Releases

on:
  workflow_dispatch:

jobs:
  create_releases:
    name: Create Releases
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - shell: bash
        run: |
          python -c "import platform, os; print(platform.libc_ver())"

